apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: externaldb  #Application's namespace
type: kubernetes.io/basic-auth
stringData:
  username: K10Admin # required field for kubernetes.io/basic-auth
  password: Veeam123! # required field for kubernetes.io/basic-auth
  host: external-mongodb.externaldb.svc.cluster.local
  port: '27017'
  db_name: k10mongodb #DB to be protected, only required for single database backup
  auth_database: admin #Only required for single database backup