apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: externaldb  
type: kubernetes.io/basic-auth
stringData:
  username: K10Admin # required field for kubernetes.io/basic-auth
  password: Veeam123! # required field for kubernetes.io/basic-auth
