apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: appexternaldb
type: kubernetes.io/basic-auth
stringData:
  username: stock # required field for kubernetes.io/basic-auth
  password: Veeam123! # required field for kubernetes.io/basic-auth  