apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: appexternaldb  #Application's namespace
type: kubernetes.io/basic-auth
stringData:
  username: kastenbp # required field for kubernetes.io/basic-auth
  password: Veeam123! # required field for kubernetes.io/basic-auth
  host: external-postgresql.appexternaldb.svc.cluster.local
  port: '5432'
  db_name: kastenbp #DB to be protected, only required for single database backup
      