apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: appexternaldb
data:
  host: external-postgresql.appexternaldb.svc.cluster.local
  port: '5432'
  db_name: stock #DB to be protected, only required for single database backup    